Feauture/path for bellman ford
Optimization-Methods-Project-OmSU-2024/Shortest-path-problem pull request #10
Opened 2024-03-09 06:10 UTC by EkaterinaDerisheva

Реализовала метод Path для БФ, аналогичный методу PathForDijkstra

2024-03-09 12:41 UTC, konovalovme2 requested changes

2024-03-09 12:41 UTC, konovalovme2 commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +        int distance = pointersAndDistances.getDistances()[t];
Здесь distance double должен быть, как в Дейкстре
```suggestion
        double distance = pointersAndDistances.getDistances()[t];
```

2024-03-09 13:06 UTC, RuslanShaikin requested changes
Такая же ситуация, как и в ветке с Дейкстрой. Оставил suggestions, чтобы было понятнее. Сами алгоритмы работают правильно.

2024-03-09 13:06 UTC, RuslanShaikin commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +        PointersAndDistances pointersAndDistances = new PointersAndDistances(dijkstra(s, graphWeightMatrix));
```suggestion
        PointersAndDistances pointersAndDistances = dijkstra(s, graphWeightMatrix);
```
Можно сделать вот так

2024-03-09 13:06 UTC, RuslanShaikin commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +        List<Integer> pathList = new ArrayList<>();
Один из вариантов, который фиксит проблему с addFirst
```suggestion
        LinkedList<Integer> pathList = new LinkedList<>(graphWeightMatrix[0].length);
```
Лично мне не очень нравится, я бы предпочел не работать с LinkedList, но в общем и целом вполне допустим

2024-03-10 09:24 UTC, RuslanShaikin approved these changes
Все гуд

2024-03-10 09:29 UTC, konovalovme2 approved these changes
Всё гуд

2024-03-10 09:35 UTC, merged