Feauture/path for dijkstra
Optimization-Methods-Project-OmSU-2024/Shortest-path-problem pull request #5
Opened 2024-03-08 15:38 UTC by EkaterinaDerisheva

Сделала метод PathFordijkstra и добавила конструктор копирования в PointersAndDistances. Пока без тестов

2024-03-09 07:51 UTC, NastyaShchitova approved these changes
Алгоритм верный.

2024-03-09 08:11 UTC, RuslanShaikin requested changes
Немного придрался к паре мест, но очень критично сделать правильный тип данных

2024-03-09 08:11 UTC, RuslanShaikin commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +        List<Integer> pathList = new ArrayList<>();
Можно задать initial capacity - количество вершин в графе

2024-03-09 08:11 UTC, RuslanShaikin commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +        int[] d = dijkstra(s, graphWeightMatrix).getDistances();
Расстояния выражаются типом double (1)

2024-03-09 08:11 UTC, RuslanShaikin commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +        int distance = d[t];
Расстояния выражаются типом double (2)

2024-03-09 08:11 UTC, RuslanShaikin commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +            v = u;
Можно обойтись без создания новой переменной u (сразу использовать p[v]

2024-03-09 08:11 UTC, RuslanShaikin commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +        int v = t;
Я так понял, здесь подразумевается, что начальная вершина - это t, а не s (если это так то нужно поменять их местами)

2024-03-09 08:21 UTC, RuslanShaikin requested changes
Нужно исправить тип у distance

2024-03-09 08:21 UTC, RuslanShaikin commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +        int distance = pointersAndDistances.getDistances()[t];
distance все еще типа int

2024-03-09 08:21 UTC, RuslanShaikin commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +        PointersAndDistances pointersAndDistances = new PointersAndDistances(dijkstra(s, graphWeightMatrix));
не совсем понятно зачем создавать PnD через конструктор копирования если возвращаемое значение алгоритма Дейкстры уже является PnD?

2024-03-09 08:51 UTC, RuslanShaikin requested changes
Уф

2024-03-09 08:51 UTC, RuslanShaikin commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +            pathList.addFirst(u);
Критический момент:
1) Метод addFirst присущ только классу LinkedList
2) Даже если заменить присвоенный тип в строке 13 с ArrayList на Linked, итоговый объект сможет использовать только те методы, которые есть у заявленного типа (просто List)
Итоговый результат не скомпилируется
Предлагаю два решения:
1) Заменить в строке 13 как заявленный так и присвоенный тип на LinkedList
2) Переделать алгоритм без использования метода addFirst

2024-03-09 10:11 UTC, EkaterinaDerisheva commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +        int distance = pointersAndDistances.getDistances()[t];
я не знаю, что сейчас в актуальной версии проекта, но когда я этот код писала, то у PnD был int distance

2024-03-09 10:12 UTC, EkaterinaDerisheva commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +        PointersAndDistances pointersAndDistances = new PointersAndDistances(dijkstra(s, graphWeightMatrix));
я не придумала как это сделать по-другому (только вариант из первого коммита, но он плох тем, что два раза вызывается алгоритм)

2024-03-09 10:14 UTC, EkaterinaDerisheva commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +            pathList.addFirst(u);
окей, попробую пофиксить

2024-03-09 15:45 UTC, EkaterinaDerisheva commented on src/main/java/org/shortest_path_problem/omsu/Path.java
> +            pathList.addFirst(u);
кстати, на самом деле метод addFirst есть и в ArrayList, но работает он не совсем так, как в LinkedList

2024-03-10 06:48 UTC, RuslanShaikin approved these changes
Все работает как надо. Отличная работа!

2024-03-10 07:00 UTC, merged